### ISSUE TITLE
Unable to make the plugin work with Gopls

### ISSUE THREAD

**Issue by hakro** [panekj/lapce-go#3]
Hi,

I'm using the latest Lapce version 0.2.2
Installed the Go Plugin, and Gopls. I also configured its correct path in the settings.

Yet nothing happens with Go files. I just get an error message in the editor, but I don't get any autocompletion, or Go to definition, or anything. Restarting the editor, and using the nightly build does not help either.

Here is a screenshot with the settings page, and the error messages that I get : 

![2022-11-09_20-12](https://user-images.githubusercontent.com/3624853/200920816-6c0c9c05-6e2f-4a4d-894f-185fb3e53681.png)

**Comment by panekj** [comment]
Should be fixed as of `v2022.11.10`

**Comment by surendrajat** [comment]
Still getting the second error:

<img width="383" alt="lapce_go" src="https://user-images.githubusercontent.com/11215000/212291072-730e8d57-d7a5-4565-a4b6-9887cf01afd4.png">
